#----------#
#--ESTRAL--#
#----------#

# writes DCD_items.txt and ItemName.json from the same lists DCD_Core.lua loops over.
# change a list here and there together, or the lua lookup and the scripts drift apart.
#
#   powershell -ExecutionPolicy Bypass -File tools\gen_cards.ps1

$ErrorActionPreference = "Stop"

$root    = Split-Path -Parent $PSScriptRoot
$media   = Join-Path $root "Contents\mods\DeadCourtDeck\42\media"
$scripts = Join-Path $media "scripts\DCD_items.txt"
$names   = Join-Path $media "lua\shared\Translate\EN\ItemName.json"
$icons   = Join-Path $media "textures"

$module = "DeadCourtDeck"

$suits      = @("Hearts", "Diamonds", "Clubs", "Spades")
$ranks      = @("A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K")
$courtRanks = @("J", "Q", "K")
$races      = @("Human", "Goblin", "Elf", "Dwarf")
$tiers      = @("Standard", "Bronze", "Silver", "Gold")

$rankNames = @{ A = "Ace"; J = "Jack"; Q = "Queen"; K = "King" }

# the common tier is the plain card, so its name carries no tier word: "7 of Hearts" against
# "Gold Goblin King of Spades". menus still say Standard when naming a whole set.
function Get-CardName([string]$tier, [string]$rest) {
    if ($tier -eq "Standard") { return $rest }
    return "$tier $rest"
}

$items = New-Object System.Collections.Generic.List[object]

# pack first, so it sits at the top of the script file and the debug item list.
$items.Add([pscustomobject]@{
    Type = "CardPack"; Icon = "DCD_CardPack"; Name = "Dead Court Card Pack"; Weight = "0.05"
})

foreach ($suit in $suits) {
    foreach ($rank in $ranks) {
        $rankName = if ($rankNames.ContainsKey($rank)) { $rankNames[$rank] } else { $rank }
        $isCourt = $courtRanks -contains $rank

        foreach ($tier in $tiers) {
            if ($isCourt) {
                foreach ($race in $races) {
                    $key = "${suit}_${rank}_${race}_${tier}"
                    $items.Add([pscustomobject]@{
                        Type = "Card_$key"; Icon = "DCD_$key"; Weight = "0.01"
                        Name = (Get-CardName $tier "$race $rankName of $suit")
                    })
                }
            } else {
                $key = "${suit}_${rank}_${tier}"
                $items.Add([pscustomobject]@{
                    Type = "Card_$key"; Icon = "DCD_$key"; Weight = "0.01"
                    Name = (Get-CardName $tier "$rankName of $suit")
                })
            }
        }
    }
}

# ---- scripts ----

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/*----------*/")
[void]$sb.AppendLine("/*--ESTRAL--*/")
[void]$sb.AppendLine("/*----------*/")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("/* GENERATED by tools/gen_cards.ps1. edit the generator, not this file. */")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("module $module")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("`timports")
[void]$sb.AppendLine("`t{")
[void]$sb.AppendLine("`t`tBase")
[void]$sb.AppendLine("`t}")

foreach ($it in $items) {
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("`titem $($it.Type)")
    [void]$sb.AppendLine("`t{")
    [void]$sb.AppendLine("`t`tDisplayCategory`t`t= Entertainment,")
    [void]$sb.AppendLine("`t`tItemType`t`t= base:normal,")
    [void]$sb.AppendLine("`t`tDisplayName`t`t= $($it.Name),")
    [void]$sb.AppendLine("`t`tIcon`t`t`t= $($it.Icon),")
    [void]$sb.AppendLine("`t`tWeight`t`t`t= $($it.Weight),")
    [void]$sb.AppendLine("`t`tWorldStaticModel`t= CardDeck,")
    [void]$sb.AppendLine("`t}")
}

[void]$sb.AppendLine("}")

# no bom: the script parser reads the first bytes as part of the first token.
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($scripts, $sb.ToString(), $utf8)

# ---- translations ----

$jb = New-Object System.Text.StringBuilder
[void]$jb.AppendLine("{")
for ($i = 0; $i -lt $items.Count; $i++) {
    $it = $items[$i]
    $comma = if ($i -lt $items.Count - 1) { "," } else { "" }
    [void]$jb.AppendLine("  `"$module.$($it.Type)`": `"$($it.Name)`"$comma")
}
[void]$jb.AppendLine("}")
[System.IO.File]::WriteAllText($names, $jb.ToString(), $utf8)

# ---- art report ----

$missing = @()
foreach ($it in $items) {
    $png = Join-Path $icons ("Item_" + $it.Icon + ".png")
    if (-not (Test-Path $png)) { $missing += ("Item_" + $it.Icon + ".png") }
}

Write-Host ("wrote {0} items to {1}" -f $items.Count, $scripts)
Write-Host ("wrote {0} names to {1}" -f $items.Count, $names)

if ($missing.Count -eq 0) {
    Write-Host "all icons present."
} else {
    Write-Host ("{0} of {1} icons missing from {2}" -f $missing.Count, $items.Count, $icons)
    $report = Join-Path $PSScriptRoot "missing_icons.txt"
    [System.IO.File]::WriteAllLines($report, $missing, $utf8)
    Write-Host ("full list in {0}" -f $report)
}
